name: CI

on:
  push:
    branches:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#excluding-paths
    - '*'
    - '!**gpu'

jobs:
  test:
    # https://help.github.com/en/articles/virtual-environments-for-github-actions#supported-virtual-environments
    runs-on: ubuntu-20.04

    # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables
    env:
      PYTHONWARNINGS: 'ignore'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - run: pip install -U pytest
    - run: pip install -U scipy
    - run: pip install -f pip install torch

    - run: pip install --no-index .
    - run: pytest tests/python/cpu
